export const ADD_ACTION = 'ADD_ACTION'
export const UPDATE_ACTION = 'UPDATE_ACTION'
export const DELETE_ACTION = 'DELETE_ACTION'

export const ADD_CHARACTER = 'ADD_CHARACTER'
export const UPDATE_CHARACTER = 'UPDATE_CHARACTER'
export const DELETE_CHARACTER = 'DELETE_CHARACTER'

export const ADD_WORLD = 'ADD_WORLD'
export const UPDATE_WORLD = 'UPDATE_WORLD'
export const DELETE_WORLD = 'DELETE_WORLD'